### ISSUE TITLE
Module not found: Error: Can't resolve './_config' in '/Users/mos/pubpub-editor/stories'

### ISSUE THREAD

**Issue by mattiasostmar** [pubpub/pubpub-editor#2]
Hi! I tried to follow the installations instructions (I'm new to Node, NPM etc) and set up a local installation of PubPub-Editor for trying it out as an editor on my Mac OS X 10.13. 

The editor is running at localhost:9002 (please, clarify the expected in docs for noobs like me), but I get the following error message in the GUI.

What have I done wrong? 

`ERROR in ./stories/_utilities.js
Module not found: Error: Can't resolve './_config' in '/Users/mos/pubpub-editor/stories'
 @ ./stories/_utilities.js 20:14-34
 @ ./stories/fileStories.js
 @ ./stories Stories\.js$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js`

**Comment by mattiasostmar** [comment]
I noticed that line 3 in `/stories/_utilities.js` asks for awsConfig in a non-existent file `_config`(.js?) in `./stories`.

Is it only supposed to be run on AWS? 

How can I make it run on my local machine?

**Comment by isTravis** [comment]
Thanks so much for the issue! The `_config.js` file is used to store credentials to an AWS S3 bucket which is used to store uploaded files (e.g. images, videos). 

I've added [some descriptive text](https://github.com/pubpub/pubpub-editor#to-install-and-run-storybook) to the README and also added a `stories/_sampleConfig.js` that can be used to as a template.

Let me know if that is sufficiently clear or if the problem persists!
