### ISSUE TITLE
Copy and pasting code blocks collapses line breaks

### ISSUE THREAD

**Issue by joeltg** [pubpub/pubpub-editor#22]
1. create a code _block_ with a few lines
2. copy the whole block
3. paste elsewhere in the pub

The text gets pasted as _inline formatted_ code, and the line breaks get replaced with spaces.

**Comment by idreyn** [comment]
Fixed in #23.

**Comment by idreyn** [comment]
(@joeltg we're merging this into the `v6` editor so you might not see this reflected for a few weeks)
