### ISSUE TITLE
Is it possible to enable the static formatting bar shown on the ProseMirror examples?

### ISSUE THREAD

**Issue by meetbryce** [pubpub/pubpub-editor#9]
As well as the popover version that shows when you highlight text?

**Comment by isTravis** [comment]
Will the latest master release, no. We are however working on a v5 of the editor that will include a <HeaderMenu /> component. You can see that work in progress here [https://github.com/pubpub/pubpub-editor/tree/v5/src/addons/HeaderMenu](https://github.com/pubpub/pubpub-editor/tree/v5/src/addons/HeaderMenu).
